# Generated by Django 5.2.6 on 2025-10-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('module', 'module'), ('VRAM', 'VRAM'), ('fan', 'fan')], max_length=100),
        ),
    ]
