# Generated by Django 5.2.6 on 2025-09-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adddess_line1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='adddess_line2',
            new_name='address_line2',
        ),
    ]
