# Generated by Django 5.2.6 on 2025-10-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_adddess_line1_order_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='province',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
