# Generated by Django 5.2.6 on 2025-10-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='province',
            field=models.CharField(max_length=100),
        ),
    ]
